# -*- coding: utf-8 -*-
"""Retail Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103zYPpMqOC4GDEd5vxPyJMwqzMxmxw6d

# Retail Sales Analysis Project

## Objective
This project analyzes retail sales data using:
- Python for data generation & analysis
- SQL (SQLite) for data storage & querying
- EDA and visualization for insights

Tools Used:
- Python
- SQLite (SQL)
- Pandas
- Matplotlib & Seaborn
"""

import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

np.random.seed(42)

data_size = 500

data = {
    "order_id": range(1, data_size + 1),
    "order_date": pd.date_range(start="2024-01-01", periods=data_size, freq="D"),
    "customer_id": np.random.randint(1000, 1100, data_size),
    "product": np.random.choice(
        ["Laptop", "Mobile", "Tablet", "Headphones", "Smartwatch"], data_size),
    "category": np.random.choice(
        ["Electronics", "Accessories"], data_size),
    "quantity": np.random.randint(1, 5, data_size),
    "price": np.random.randint(100, 1500, data_size),
    "region": np.random.choice(
        ["North", "South", "East", "West"], data_size)
}

df = pd.DataFrame(data)
df["total_amount"] = df["quantity"] * df["price"]

display(df.head())

conn = sqlite3.connect("retail_sales.db")
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS sales")

cursor.execute("""
CREATE TABLE sales (
    order_id INTEGER,
    order_date TEXT,
    customer_id INTEGER,
    product TEXT,
    category TEXT,
    quantity INTEGER,
    price INTEGER,
    total_amount INTEGER,
    region TEXT
)
""")

conn.commit()

df.to_sql("sales", conn, if_exists="append", index=False)

pd.read_sql("SELECT COUNT(*) AS total_rows FROM sales", conn)

query = """
SELECT region, SUM(total_amount) AS total_sales
FROM sales
GROUP BY region
"""
region_sales = pd.read_sql(query, conn)
display(region_sales)

plt.figure(figsize=(8,5))
sns.barplot(x="region", y="total_sales", data=region_sales)
plt.title("Total Sales by Region")
plt.show()

query = """
SELECT product, SUM(quantity) AS total_units_sold
FROM sales
GROUP BY product
ORDER BY total_units_sold DESC
"""
product_sales = pd.read_sql(query, conn)
display(product_sales)

plt.figure(figsize=(8,5))
sns.barplot(x="product", y="total_units_sold", data=product_sales)
plt.title("Top Selling Products")
plt.show()

query = """
SELECT substr(order_date,1,7) AS month, SUM(total_amount) AS revenue
FROM sales
GROUP BY month
ORDER BY month
"""
monthly_sales = pd.read_sql(query, conn)
display(monthly_sales.head())

plt.figure(figsize=(10,5))
plt.plot(monthly_sales["month"], monthly_sales["revenue"], marker='o')
plt.xticks(rotation=45)
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.show()

display(df.describe())

df.isnull().sum()

plt.figure(figsize=(8,5))
sns.histplot(df["total_amount"], bins=30, kde=True)
plt.title("Order Value Distribution")
plt.show()

"""## Key Insights
- West and North regions contribute the highest revenue
- Laptops and Mobiles are top-selling products
- Monthly revenue shows a steady upward trend
- Most orders fall within mid-range order values

## Conclusion
This project demonstrates:
- Integration of SQL within Python
- Real-world data analysis workflow
- Effective EDA and visualization techniques
- Google Colab compatible project execution
"""